[package]
name = "notos_sdk"
version = "0.2.2"
edition = "2021"

[dependencies]
eframe = { version = "0.29.1", default-features = false }
egui = { version = "0.29.1", default-features = false }
log = "0.4"
